import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
  AspectRatio
} from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Title, WorkImage, Meta } from '../../components/work'
import P from '../../components/paragraph'
import Layout from '../../components/layouts/article'

const Work = () => (
  <Layout title="Weee">
    <Container>
      <Title>
        Cognition experiment <Badge>2023-2024</Badge>
      </Title>
      <P>
        An experiment website studying the relationship of memory and age
      </P>
      <List ml={4} my={4}>
        <ListItem>
          <Meta>Website</Meta>
          <Link href="https://online-exp-fa0f1071162c.herokuapp.com/">
            https://online-exp-fa0f1071162c.herokuapp.com/ <ExternalLinkIcon mx="2px" />
          </Link>
        </ListItem>
        <ListItem>
          <Meta>Platform</Meta>
          <span>Web</span>
        </ListItem>
        <ListItem>
          <Meta>Stack</Meta>
          <span>Angular / PrimeNG / AWS / Heroku</span>
        </ListItem>

      </List>
      <List>

        <ListItem>
          1. Developed a user-friendly UI with Angular 14-16 and PrimeNG for the store intro-page in the upcoming Global+ service, including store info, products display, and customer reviews components as well as search and navigation functionalities.
        </ListItem>
        <ListItem>
          2. Orchestrated a comprehensive UX design including the creation of a detailed Persona, a User Journey Map, interactive wireframes and prototypes with Figma, prioritizing a seamless user experience and visually engaging interface.
        </ListItem>
        <ListItem>
          3. Achieved lazy-loading using Angular standalone components to optimize resource utilization and significantly improve various web vitals.
        </ListItem>
        <ListItem>
          4. Realized infinite scroll for customer review list to provide efficient loading of additional content as the user scrolls down and added customized sorting based on liked numbers and post time.
        </ListItem>
        <ListItem>
          5. Created a carousel for video reviews with video-to-GIF preview feature using ffmpeg.js to display the most captivating snippet on loop to attract user’s attention.
        </ListItem>
        <ListItem>
          6. Performed CRUD operations on shopping cart items using RESTful API, enabling efficient and reliable updates, retrievals, and deletions of products.
        </ListItem>
        <ListItem>
          7. Implemented real-time updates for inventory of discounted products and remaining time of promotion using WebSockets API and observable in RxJS, ensuring low-latency communication and boosting user purchases.
        </ListItem>
        <ListItem>
          8. Presented the products quantity sold by merchants by product segmented in a Doughnut chart using ngx-charts, providing users with insight into the merchants’ business focus.
        </ListItem>
        <ListItem>
          9. Utilized an HTTP interceptor to attach JWT to requests headers, manage server responses for all role-based user operations, and secured routes with guards for streamlined access control.
        </ListItem>
        <ListItem>
          10. Set up automated unit testing using Jasmine/Karma to validate functionalities and UI components for better code coverage and maintainability; performed e2e testing using Cypress to verify the user flow from adding items to the cart to placing an order across various browsers.
        </ListItem>
        <ListItem>
          11. Deployed the application to Amazon CodePipeline, used S3 to store build artifacts generated by CodeBuild and host static assets, achieving automated and efficient CI/CD processes.
        </ListItem>
        <ListItem>
          12. Utilized Git/Github for version control and collaborated with the team (10+ developers) using Agile Methodology and JIRA for issue tracking and project management.
        </ListItem>
        <ListItem>
          13. Collaborated with cross-functional teams to understand, break down requirements, develop comprehensive test cases to cover various scenarios and edge cases and set testing timelines based on project deadlines.
        </ListItem>
        <ListItem>
          14. Designed automated UI testing (snapshot testing) scripts using Jest and React Testing Library to continuously validate the platform’s UI features, ensuring consistent UI rendering and detecting unintended changes.
        </ListItem>
      </List >

    </Container>
  </Layout>
)

export default Work
export { getServerSideProps } from '../../components/chakra'
